# Generated by Django 4.2.3 on 2023-07-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PersonOfContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('direct_or_recruiter', models.CharField(choices=[('Direct', 'Direct'), ('Recruiter', 'Recruiter')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('notes', models.TextField()),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_search.company')),
                ('person_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_search.personofcontact')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='person_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_search.personofcontact'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=60)),
                ('role_title', models.CharField(blank=True, max_length=60, null=True)),
                ('job_description', models.CharField(blank=True, max_length=120, null=True)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Active', 'Active'), ('Dead', 'Dead')], max_length=10)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_search.company')),
                ('contact_events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_search.contactevent')),
                ('person_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_search.personofcontact')),
            ],
        ),
    ]
